name: Web Scraping Pipeline

on:
  push:
    branches:
      - main  # Se ejecutará cuando se haga push a la rama principal

jobs:
  scrape:
    runs-on: ubuntu-latest  # Usa una máquina virtual con Ubuntu

    steps:
    # 1. Descargar el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar Python (actualizado a Python 3.10)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Ahora estamos usando Python 3.10

    # 3. Instalar dependencias desde requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Ejecutar el script de scraping
    - name: Run scraping script
      run: python src/ejecucion.py  # Asegúrate de que esta ruta sea correcta

    # 5. Opcional: Cargar el archivo HTML generado como artefacto
    - name: Upload HTML artifact
      if: success()  # Solo si el flujo de trabajo fue exitoso
      uses: actions/upload-artifact@v3
      with:
        name: productos_mercadolibre  # Nombre del artefacto
        path: productos_mercadolibre.html  # Ruta del archivo HTML generado