name: Web Scraping Pipeline

on:
  push:
    branches:
      - main  

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Cambiar si usas otra versión

      # 3. Instalar dependencias desde requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Ejecutar el script de scraping
      - name: Run scraping script
        run: python src/ejecucion.py  # Ruta correcta para ejecutar el script

      # 5. Opcional: Cargar el archivo HTML generado como artefacto
      - name: Upload HTML artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: productos_mercadolibre
          path: productos_mercadolibre.html